# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/machine-learning',
                'doc_host': 'https://najmehtaleb.github.io',
                'git_url': 'https://github.com/najmehtaleb/machine-learning',
                'lib_path': 'machine_learning'},
  'syms': {}}