project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  
  navbar:
    search: true
    title: Machine Learning
    left:
      - text: Home
        href: https://najmehtaleb.github.io/my-site/
        
    right:
      - icon: github
        href: https://github.com/najmehtaleb/machine-learning
      - icon: twitter
        href: https://twitter.com/NajmehTaleb
    
    
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    contents:
    
    - section: Python Machine Learning Ecosystem
      contents: 
      - 01-ml-ecosystem/intro.ipynb
      - 01-ml-ecosystem/numpy.ipynb
      - 01-ml-ecosystem/panda.ipynb
      - 01-ml-ecosystem/matplotlib.ipynb
      
    - section: End-to-End Machine Learning Process
      contents: 
      - 02-end-to-end/intro.ipynb
      - 02-end-to-end/steps.ipynb
      
    - section: Data Preparation
      contents: 
      - 03-data-preparation/data-cleaning.ipynb
      - 03-data-preparation/data-leakage.ipynb
      - 03-data-preparation/data-transforms.ipynb
      - 03-data-preparation/dimensionality-reduction.ipynb
      - 03-data-preparation/feature-selection.ipynb
      
   - section: Ensemble Learning Algorithms
      contents: 
      - 04-ensemble-learning/intro.ipynb
      - 04-ensemble-learning/multiple-models.ipynb
      - 04-ensemble-learning/bagging.ipynb
      - 04-ensemble-learning/boosting.ipynb   
      - 04-ensemble-learning/stacking.ipynb
      
    - section: XGboost
      contents: 
      - 05-xgboost/xgboost.ipynb      

metadata-files: [nbdev.yml]
