project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  
  navbar:
    search: true
    title: Machine Learning
    left:
      - text: Home
        href: https://najmehtaleb.github.io/my-site/
        
    right:
      - icon: github
        href: https://github.com/najmehtaleb/machine-learning
      - icon: twitter
        href: https://twitter.com/NajmehTaleb
    
    
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    contents:
    - section: Python Machine Learning Ecosystem
      contents: 
      - 00-ml-ecosystem/intro.ipynb
      - 00-ml-ecosystem/numpy.ipynb
      - 00-ml-ecosystem/panda.ipynb
      - 00-ml-ecosystem/matplotlib.ipynb
    - section: End-to-End Machine Learning Process
      contents: 
      - 01-end-to-end/intro.ipynb
      - 01-end-to-end/steps.ipynb
      

metadata-files: [nbdev.yml]
