project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  
  navbar:
    search: true
    title: Machine Learning
    left:
      - text: Home
        href: https://najmehtaleb.github.io/my-site/
        
    right:
      - icon: github
        href: https://github.com/najmehtaleb/machine-learning
      - icon: twitter
        href: https://twitter.com/NajmehTaleb
    
    
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    contents:
    - section: Quick Start
      contents: 
      - quick-start/intro.ipynb
      - quick-start/steps.ipynb
      - quick-start/datasets.ipynb
      

metadata-files: [nbdev.yml]
